### ISSUE TITLE
Spawn

### ISSUE THREAD

**Issue by jomisoac** [w0dm4n/Thanadolos#1]
Database include monster spawm and item interactive spawn?

**Comment by Sparkymod** [comment]
Severity	Code	Description	Project	File	Line	Suppression State
Error	C2039	'convert': is not a member of 'camp::util::detail'	Thanadolos World	c:\users\rafa\desktop\installing libraries\camp-master\include\camp\util.hpp	147

**Comment by w0dm4n** [comment]
@rafamod You certainly have a wrong version of camp, clone this : https://github.com/tegesoft/camp and take the headers folder

**Comment by w0dm4n** [comment]
@jomisoac There is no monster spawn, it's not developped yet on the emulator.
