### ISSUE TITLE
There is a problem with auth..

### ISSUE THREAD

**Issue by Sparkymod** [w0dm4n/Thanadolos#3]
Salut!

i was wondering if you can help me here pls.

http://prntscr.com/fuvacd

is an error of LINK2005 with an object "Already defined in Auth.obj"

**Comment by Sparkymod** [comment]
Now all done, is just a bad "sqlapi.lib" is just the one that is in " /x86_x64/lib"

**Comment by w0dm4n** [comment]
Hey, you need to compile the emulator in 64bit for the sqlapi, for the re-include error check the auth main and try to comment some stuff

**Comment by Sparkymod** [comment]
Ok! Thanks i really want to this works and at least do the translate for English/Spanish content.
