### ISSUE TITLE
Client Ticket?

### ISSUE THREAD

**Issue by Nooblets** [w0dm4n/Thanadolos#7]
Not sure what's wrong here, I'm using the 2.41 version and it doesn't seem to recognize the ticket?
![thanadolos world_2018-02-08_16-34-55](https://user-images.githubusercontent.com/36271607/35981718-4129d742-0cee-11e8-94c6-a640d5593f5d.png)

**Comment by w0dm4n** [comment]
You certainly dont have the good DofusInvoker on the client

**Comment by Nooblets** [comment]
Do you think you could provide me with a correct DofusInvoker? Since I currently got one from DozenOfElites ( Rebirth DofusInvoker )

**Comment by w0dm4n** [comment]
Here is a list of DofusInvoker, one of these should be the good one: http://ge.tt/7qInyUo2
I'm not sure which one is, sorry 😙

**Comment by Nooblets** [comment]
Sadly 2 of these get me past the login screen, but still give me the ticket problem. Thanks for trying to help me though! Appreciate it.

**Comment by w0dm4n** [comment]
Okay, good luck, i hope you will solve your problem !
